databaseChangeLog = {
	include file: 'initial-schema.groovy'
	include file: 'repository-to-plugin.groovy'
	include file: 'refactor-tasks.groovy'
	include file: 'create-qaa-schema.groovy'
	include file: 'refactor-task-steps.groovy'
	include file: 'documentations-commentable.groovy'
	include file: 'task-type-taxonomy.groovy'
	include file: 'reflection-answer-rating.groovy'
	include file: 'settings-to-common-plugin.groovy'
	include file: 'taxonomy-term-refactor.groovy'
	include file: 'settings-add-field.groovy'
	include file: 'settings-add-valuelist.groovy'
	include file: 'updatetrigger-commentable.groovy'
	include file: 'taxonomy-company.groovy'
	include file: 'task-expiry.groovy'
}
